# Generated by Django 3.0.5 on 2020-08-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='email',
            field=models.CharField(default='', max_length=70),
        ),
    ]
